[package]
name = "ragu_arithmetic"
version.workspace = true
authors.workspace = true
description = """
Fundamental arithmetic traits and utilities for the Ragu project
"""
license.workspace = true
edition.workspace = true
rust-version.workspace = true

readme = "README.md"
repository.workspace = true
documentation = "https://docs.rs/ragu_arithmetic"
categories = ["cryptography", "mathematics", "algorithms", "science", "no-std"]
keywords = []

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", "katex-header.html"]
all-features = true

[features]
accel-fft = ["std", "dep:zcash-pasta-accel"]
accel-msm = ["std", "dep:zcash-pasta-accel"]
alloc = []
default = ["alloc"]
multicore = ["maybe-rayon/threads", "std"]
std = []

[lib]
bench = false

[dependencies]
ff = { workspace = true }
pasta_curves = { workspace = true }
ragu_macros = { path = "../ragu_macros", version = "0.0.0" }
rand = { workspace = true }
maybe-rayon = { workspace = true }
zcash-pasta-accel = { path = "../../../../crates/zcash-pasta-accel", optional = true }

[dev-dependencies]
proptest = { workspace = true }
gungraun = { workspace = true }
criterion = { workspace = true }
ragu_testing = { path = "../ragu_testing", version = "0.0.0" }

[[bench]]
name = "arithmetic"
harness = false

[[bench]]
name = "msm_criterion"
path = "benches/criterion/msm.rs"
harness = false

[[bench]]
name = "fft_criterion"
path = "benches/criterion/fft.rs"
harness = false
