use alloc::{vec, vec::Vec};

#[cfg(feature = "accel-fft")]
use alloc::{format, string::String};

use ff::PrimeField;

#[cfg(feature = "accel-fft")]
use core::sync::atomic::{AtomicU64, Ordering};

/// Number of exact `log2(domain_size)` buckets recorded in [`AccelFftStats`].
#[cfg(feature = "accel-fft")]
pub const ACCEL_FFT_LOG2_BUCKETS: usize = 65;

/// Runtime counters for feature-gated FFT workload profiling.
#[cfg(feature = "accel-fft")]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AccelFftStats {
    /// Number of forward FFT transforms.
    pub ffts: u64,

    /// Number of inverse FFT transforms.
    pub iffts: u64,

    /// Sum of domain sizes across forward and inverse FFT transforms.
    pub total_domain_size: u64,

    /// Transform count by exact `log2(domain_size)` bucket.
    ///
    /// Index `i` records transforms over domains of size `2^i`. Values whose
    /// `log2` is greater than or equal to [`ACCEL_FFT_LOG2_BUCKETS`] are
    /// saturated into the final bucket.
    pub domain_log2_buckets: [u64; ACCEL_FFT_LOG2_BUCKETS],
}

#[cfg(feature = "accel-fft")]
impl Default for AccelFftStats {
    fn default() -> Self {
        Self {
            ffts: 0,
            iffts: 0,
            total_domain_size: 0,
            domain_log2_buckets: [0; ACCEL_FFT_LOG2_BUCKETS],
        }
    }
}

#[cfg(feature = "accel-fft")]
static ACCEL_FFTS: AtomicU64 = AtomicU64::new(0);

#[cfg(feature = "accel-fft")]
static ACCEL_IFFTS: AtomicU64 = AtomicU64::new(0);

#[cfg(feature = "accel-fft")]
static ACCEL_FFT_TOTAL_DOMAIN_SIZE: AtomicU64 = AtomicU64::new(0);

#[cfg(feature = "accel-fft")]
static ACCEL_FFT_LOG2_BUCKET_COUNTS: [AtomicU64; ACCEL_FFT_LOG2_BUCKETS] =
    [const { AtomicU64::new(0) }; ACCEL_FFT_LOG2_BUCKETS];

/// Returns current FFT workload profiling counters.
#[cfg(feature = "accel-fft")]
pub fn accel_fft_stats() -> AccelFftStats {
    let mut domain_log2_buckets = [0; ACCEL_FFT_LOG2_BUCKETS];
    for (bucket, counter) in domain_log2_buckets
        .iter_mut()
        .zip(ACCEL_FFT_LOG2_BUCKET_COUNTS.iter())
    {
        *bucket = counter.load(Ordering::Relaxed);
    }

    AccelFftStats {
        ffts: ACCEL_FFTS.load(Ordering::Relaxed),
        iffts: ACCEL_IFFTS.load(Ordering::Relaxed),
        total_domain_size: ACCEL_FFT_TOTAL_DOMAIN_SIZE.load(Ordering::Relaxed),
        domain_log2_buckets,
    }
}

/// Formats FFT workload profiling counters for benchmark and profiling logs.
#[cfg(feature = "accel-fft")]
pub fn format_accel_fft_stats(stats: &AccelFftStats) -> String {
    let mut formatted = format!(
        "ffts={} iffts={} total_domain_size={} domain_log2_buckets={{",
        stats.ffts, stats.iffts, stats.total_domain_size
    );

    let mut wrote_bucket = false;
    for (log2_n, count) in stats.domain_log2_buckets.iter().enumerate() {
        if *count == 0 {
            continue;
        }

        if wrote_bucket {
            formatted.push(',');
        }

        formatted.push_str(&format!("log2_{log2_n}={count}"));
        wrote_bucket = true;
    }

    formatted.push('}');
    formatted
}

/// Resets FFT workload profiling counters.
#[cfg(feature = "accel-fft")]
pub fn reset_accel_fft_stats() {
    ACCEL_FFTS.store(0, Ordering::Relaxed);
    ACCEL_IFFTS.store(0, Ordering::Relaxed);
    ACCEL_FFT_TOTAL_DOMAIN_SIZE.store(0, Ordering::Relaxed);
    for counter in ACCEL_FFT_LOG2_BUCKET_COUNTS.iter() {
        counter.store(0, Ordering::Relaxed);
    }
}

#[cfg(feature = "accel-fft")]
fn record_accel_fft(log2_n: u32, inverse: bool) {
    let transform_counter = if inverse { &ACCEL_IFFTS } else { &ACCEL_FFTS };
    transform_counter.fetch_add(1, Ordering::Relaxed);

    let domain_size = if log2_n < u64::BITS {
        1_u64 << log2_n
    } else {
        u64::MAX
    };
    ACCEL_FFT_TOTAL_DOMAIN_SIZE.fetch_add(domain_size, Ordering::Relaxed);

    let bucket = (log2_n as usize).min(ACCEL_FFT_LOG2_BUCKETS - 1);
    ACCEL_FFT_LOG2_BUCKET_COUNTS[bucket].fetch_add(1, Ordering::Relaxed);
}

/// Radix-2 evaluation domain of size $n = 2^k$ generated by powers of a
/// primitive $n$-th root of unity $\omega$, consisting of the set
/// $\{1, \omega, \omega^2, \ldots, \omega^{n-1}\}$.
pub struct Domain<F> {
    /// $n$, the size of the domain
    n: usize,
    /// $\log_2(n)$, exponent such that $n = 2^{log2_n}$,
    /// where the domain size $n$ must always a power of two
    log2_n: u32,
    /// The primitive $n$-th root of unity in the field
    omega: F,
    /// Inverse of the primitive $n$-th root of unity in the field
    omega_inv: F,
    /// Inverse of $n$ in the field (as an integer) for inverse FFTs
    n_inv: F,
}

impl<F: PrimeField> Default for Domain<F> {
    fn default() -> Self {
        Domain {
            log2_n: F::S,
            n: 1 << F::S,
            omega: F::ROOT_OF_UNITY,
            omega_inv: F::ROOT_OF_UNITY_INV,
            n_inv: (F::TWO_INV).pow_vartime([F::S as u64]),
        }
    }
}

impl<F: PrimeField> Domain<F> {
    /// Initializes a new domain of size $2^k$.
    ///
    /// # Panics
    ///
    /// Panics if attempting to create a domain larger than supported by the
    /// field.
    pub fn new(k: u32) -> Self {
        assert!(
            k <= F::S,
            "tried to create a domain of size 2^{} in a field with 2-adicity {}",
            k,
            F::S
        );

        let mut tmp = Self::default();
        for _ in k..F::S {
            tmp = tmp.halve();
        }
        assert_eq!(k, tmp.log2_n);
        tmp
    }

    /// Halves the size of the evaluation domain.
    ///
    /// # Panics
    ///
    /// Panics if attempting to halve a domain of size 1.
    fn halve(&self) -> Self {
        assert!(self.log2_n != 0, "cannot halve a domain of size 1");

        let log2_n = self.log2_n - 1;
        Domain {
            log2_n,
            n: 1 << log2_n,
            omega: self.omega.square(),
            omega_inv: self.omega_inv.square(),
            n_inv: self.n_inv.double(),
        }
    }

    /// The size of the domain.
    pub fn n(&self) -> usize {
        self.n
    }

    /// The $\log_2(n)$ of this domain of size $n$.
    pub fn log2_n(&self) -> u32 {
        self.log2_n
    }

    /// Returns the generator of the domain.
    pub fn omega(&self) -> F {
        self.omega
    }

    /// Returns true if `x` is an element of this domain.
    pub fn contains(&self, x: F) -> bool {
        x.pow([self.n as u64]) == F::ONE
    }

    /// Computes the radix2 discrete Fourier transform (DFT) of a slice of
    /// generic ring elements using the Cooley-Tukey FFT algorithm.
    ///
    /// # Panics
    ///
    /// Panics if `input.len()` does not equal `self.n()`.
    pub fn ring_fft<R: crate::fft::Ring<F = F>>(&self, input: &mut [R::R]) {
        crate::fft::fft::<R>(input, self.omega, self.log2_n);
        #[cfg(feature = "accel-fft")]
        record_accel_fft(self.log2_n, false);
    }

    /// Performs the inverse operation of [`Self::ring_fft`].
    ///
    /// # Panics
    ///
    /// Panics if `input.len()` does not equal `self.n()`.
    pub fn ring_ifft<R: crate::fft::Ring<F = F>>(&self, input: &mut [R::R]) {
        crate::fft::fft::<R>(input, self.omega_inv, self.log2_n);

        for input in input.iter_mut() {
            R::scale_assign(input, self.n_inv);
        }

        #[cfg(feature = "accel-fft")]
        record_accel_fft(self.log2_n, true);
    }

    /// Computes the radix2 discrete Fourier transform (DFT) of a slice of field
    /// elements using the Cooley-Tukey FFT algorithm.
    ///
    /// # Panics
    ///
    /// Panics if `input.len()` does not equal `self.n()`.
    pub fn fft(&self, input: &mut [F]) {
        self.ring_fft::<crate::fft::FFTField<F>>(input);
    }

    /// Performs the inverse operation of [`Self::fft`].
    ///
    /// # Panics
    ///
    /// Panics if `input.len()` does not equal `self.n()`.
    pub fn ifft(&self, input: &mut [F]) {
        self.ring_ifft::<crate::fft::FFTField<F>>(input);
    }

    /// This function produces the evaluations of Lagrange basis polynomials
    /// $\ell_i(x)$ for the domain generated by powers of $\omega$ where
    /// $\omega$ is an `n`-th primitive root of unity. Returns `None` if `x` is
    /// an element of the domain, otherwise returns a vector with `amount`
    /// number of evaluations (starting at $\omega^0$).
    ///
    /// # Panics
    ///
    /// Panics if the provided `amount` exceeds `n`.
    ///
    /// # Implementation
    ///
    /// The Lagrange basis polynomials are given for a domain $D$ of size $n$
    /// generated by powers of $\omega$ where $\omega$ is a primitive $n$-th
    /// root of unity. The vanishing polynomial for this domain is
    ///
    /// $$ v(X) = \prod_{i=0}^{n - 1} (X - \omega^i) = X^n - 1. $$
    ///
    /// and so the Lagrange basis polynomials are given by
    ///
    /// $$ \ell_i(X) = \frac{(X^n - 1) b_i}{X - \omega^i} $$
    ///
    /// where
    ///
    /// $$ b_i = \prod_{j=0, j \neq i}^{n - 1} (\omega^i - \omega^j)^{-1} =
    /// \frac{\omega^i}{n} $$
    ///
    /// is the barycentric weight of $\omega^i$. Thus, given some point $x \in
    /// \mathbb{F} \setminus D$ we can compute
    ///
    /// $$ \ell_i(x) = (x - \omega^i)^{-1} \cdot \frac{(x^n - 1) \omega^i}{n}.$$
    ///
    /// Most of the work of computing these values can be shared using
    /// Montgomery's trick.
    pub fn ell(&self, x: F, amount: usize) -> Option<Vec<F>> {
        assert!(amount <= self.n);

        let xn = x.pow([self.n as u64]); // x^n
        if xn == F::ONE {
            // By definition, `x` must be an element of the domain itself. This
            // means that the coefficients returned will have a trivial value:
            // all zeroes except for the $i$-th coefficient which will be 1.

            // The implementation this function relies on `x` not being in the
            // domain. Therefore, we return None here to indicate to the caller
            // that the value `x` provided is in the domain so that this case
            // can be handled explicitly (and more efficiently).
            return None;
        }

        // Compute (x - \omega^i)^{-1} for i = 0, ..., amount - 1
        let mut denominators: Vec<F> = (0..amount)
            .scan(F::ONE, |acc, _| {
                let tmp = x - *acc;
                *acc *= self.omega;
                Some(tmp)
            })
            .collect();
        {
            let mut scratch = vec![F::ZERO; denominators.len()];
            ff::BatchInverter::invert_with_external_scratch(&mut denominators, &mut scratch);
        }

        Some(
            // (x - \omega^i)^{-1} \cdot \frac{(x^n - 1) \omega^i}{n}
            denominators
                .into_iter()
                .scan((xn - F::ONE) * self.n_inv, move |numerator, denominator| {
                    let tmp = (*numerator) * denominator;
                    *numerator *= self.omega;
                    Some(tmp)
                })
                .collect(),
        )
    }
}

#[test]
fn test_fft() {
    use ff::Field;
    use pasta_curves::Fp as F;

    use crate::eval;

    for log2_n in 1..=8 {
        let params = Domain::<F>::new(log2_n);

        let coeffs = (0..params.n)
            .map(|i| F::DELTA.pow([(i + 1) as u64]))
            .collect::<Vec<_>>();
        let mut evals = coeffs.clone();

        params.fft(&mut evals);

        {
            let mut p = F::ONE;
            for e in evals.iter().take(params.n) {
                assert_eq!(*e, eval(&coeffs, p));
                p *= params.omega;
            }
        }

        let mut coeffs_recovered = evals.clone();
        params.ifft(&mut coeffs_recovered);
        assert_eq!(coeffs, coeffs_recovered);
    }
}

#[cfg(feature = "accel-fft")]
#[test]
fn test_accel_fft_stats_record_domain_log2_buckets() {
    use ff::Field;
    use pasta_curves::Fp as F;

    reset_accel_fft_stats();

    let small = Domain::<F>::new(0);
    let mut small_input = vec![F::ONE];
    small.fft(&mut small_input);

    let larger = Domain::<F>::new(3);
    let mut larger_input = vec![F::ONE; larger.n()];
    larger.ifft(&mut larger_input);

    let stats = accel_fft_stats();
    assert_eq!(stats.ffts, 1);
    assert_eq!(stats.iffts, 1);
    assert_eq!(stats.total_domain_size, 9);
    assert_eq!(stats.domain_log2_buckets[0], 1);
    assert_eq!(stats.domain_log2_buckets[3], 1);
    assert_eq!(stats.domain_log2_buckets.iter().sum::<u64>(), 2);
}

#[cfg(feature = "accel-fft")]
#[test]
fn test_format_accel_fft_stats_includes_nonzero_log2_buckets() {
    let mut stats = AccelFftStats {
        ffts: 1,
        iffts: 2,
        total_domain_size: 24,
        ..AccelFftStats::default()
    };
    stats.domain_log2_buckets[0] = 1;
    stats.domain_log2_buckets[3] = 2;

    assert_eq!(
        format_accel_fft_stats(&stats),
        "ffts=1 iffts=2 total_domain_size=24 domain_log2_buckets={log2_0=1,log2_3=2}"
    );
}

#[test]
fn test_ell() {
    use alloc::vec;

    use ff::Field;
    use pasta_curves::Fp as F;

    use crate::eval;

    let params = Domain::<F>::new(5);

    let mut lagrange_polys = vec![];
    for i in 0..params.n {
        assert!(params.ell(params.omega.pow([i as u64]), params.n).is_none());
        let mut tmp = vec![F::ZERO; params.n];
        tmp[i] = F::ONE;
        params.ifft(&mut tmp);
        for j in 0..params.n {
            assert_eq!(
                eval(&tmp, params.omega.pow([j as u64])),
                if i == j { F::ONE } else { F::ZERO }
            );
        }
        lagrange_polys.push(tmp);
    }

    let x = F::DELTA;

    let expected = params.ell(x, params.n).unwrap();
    for (i, expected) in expected.iter().enumerate() {
        assert_eq!(eval(&lagrange_polys[i], x), *expected);
    }
}

#[test]
fn test_contains() {
    use ff::Field;
    use pasta_curves::Fp as F;

    let domain = Domain::<F>::new(5);

    // All powers of omega should be in the domain
    let mut omega_pow = F::ONE;
    for _ in 0..domain.n() {
        assert!(domain.contains(omega_pow), "omega^i should be in domain");
        omega_pow *= domain.omega();
    }

    // Random field elements should (almost certainly) not be in the domain
    assert!(!domain.contains(F::from(2u64)));
    assert!(!domain.contains(F::from(3u64)));
    assert!(!domain.contains(F::DELTA));
}

#[cfg(test)]
mod proptests {
    use pasta_curves::Fp as F;
    use proptest::prelude::*;

    use super::*;

    fn arb_fe() -> impl Strategy<Value = F> {
        (any::<u64>(), any::<u64>())
            .prop_map(|(a, b)| F::from(a) + F::from(b) * F::MULTIPLICATIVE_GENERATOR)
    }

    proptest! {
        #[test]
        fn fft_ifft_roundtrip(log2_n in 1u32..=8, seed in arb_fe()) {
            let domain = Domain::<F>::new(log2_n);
            let coeffs: Vec<F> = (0..domain.n())
                .map(|i| seed * F::from((i + 1) as u64))
                .collect();
            let mut buf = coeffs.clone();
            domain.fft(&mut buf);
            domain.ifft(&mut buf);
            prop_assert_eq!(buf, coeffs);
        }
    }
}

#[test]
#[should_panic]
fn test_domain_exceeds_max_boundary_panics() {
    use pasta_curves::Fp as F;

    let over_max = F::S + 1;
    let _domain = Domain::<F>::new(over_max);
}
